### ISSUE TITLE
Custom Pin category shadows not hiding

### ISSUE THREAD

**Issue by AndrewCusa** [wwwouaiebe/leaflet.marker.pin#8] opened 2017-11-04 02:34 UTC
When adding a category following the directions for addCategory()

(e.g.:
myInterface.addCategory ( 
	'IconCategory', 
	{ 'en' : 'Leaflet red', 'fr' : 'Leaflet rouge', 'nl' : 'Leaflet rood' }, 
	L.icon( {
		iconUrl: 'leaf-red.png',
		shadowUrl: 'leaf-shadow.png',
		iconSize:     [38, 95],
		shadowSize:   [50, 64],
		iconAnchor:   [22, 94],
		shadowAnchor: [4, 62],
		popupAnchor:  [-3, -76]
	} ) );
)
The "Hide Pins" button properly hides the iconUrl, but not the shadowURL - the shadow remains visible

Great work!

**Comment by wwwouaiebe** [comment] 2018-08-31 15:08
leaflet.marker.pin is deprecated and replaced by leaflet.TravelNotes. 
the problem is fixed in leaflet.TravelNotes

**Closed by wwwouaiebe** 2018-08-31 15:08 UTC
